spring:
  datasource:
    url: jdbc:mysql://localhost:3306/importer2?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

  jpa:
    show-sql: true
    hibernate:
      #Valida na inicialização do sistema, se o JPA conseguirá se comunicar com as entidades definidas
      ddl-auto: none
      naming:
        #Para encontrar tabelas uppercase no banco de dados, por padrão o hibernate busca tudo com lowercase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
